### ISSUE TITLE
Does not work anymore with the latest node version (v23)

### ISSUE THREAD

**Issue by theneongrey** [Teamop/merge-cobertura#2]
The error is the end of live of util.isString

FYI:
Message with node v22:
`(node:1097) [DEP0056] DeprecationWarning: The 'util.isString' API is deprecated.  Please use 'typeof arg === "string"' instead.`

**Comment by Teamop** [comment]
thanks, fixed in [v1.0.3](https://github.com/Teamop/merge-cobertura/releases/tag/v1.0.3)
